ExpenseTracker/Models/ErrorViewModel.cs
namespace ExpenseTracker.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExpenseTracker/Models/Expense.cs
using System.ComponentModel.DataAnnotations;

namespace ExpenseTracker.Models
{
    public class Expense
    {
        [Key]
        public int ExpenseId { get; set; }

        public DateTime DateOfExpense { get; set; }

        public int ExpenseAmount { get; set; }

        public int ExpenseCategoryId { get; set; }

        public ExpenseCategory ExpenseCategory { get; set; }

    }
}

ExpenseTracker/Models/ExpenseCategory.cs
using System.ComponentModel.DataAnnotations;

namespace ExpenseTracker.Models
{
    public class ExpenseCategory
    {
        [Key]
        public int ExpenseCategoryId { get; set; }

        public string ExpenseCategoryName { get; set; }
    }
}

ExpenseTracker/Controllers/ExpenseCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpenseTracker.Data;
using ExpenseTracker.Models;
using ExpenseTracker.Repository;

namespace ExpenseTracker.Controllers
{
    public class ExpenseCategoriesController : Controller
    {
        private readonly IExpenseCategory _expense;

        public ExpenseCategoriesController(IExpenseCategory expense)
        {
            _expense = expense;
        }

        public IActionResult Index()
        {
              return View(_expense.GetAll());
        }

        public IActionResult Create()
        {
            return View();
        }

     
        [HttpPost]
        public IActionResult Create(ExpenseCategory expenseCategory)
        {
            if (ModelState.IsValid)
            {
                var AlreadyExists = _expense.GetAll().Where(x => x.ExpenseCategoryName == expenseCategory.ExpenseCategoryName).FirstOrDefault();
                if (AlreadyExists == null)
                {
                    _expense.Create(expenseCategory);
                }
                else
                {

                    ViewBag.Message = string.Format(" This Category Is Already Exists !!! Please Enter New One ", expenseCategory);
                    return View();
                }
               
                return RedirectToAction("Index");
            }
            return View(expenseCategory);
        }

        // GET: ExpenseCategories/Edit/5
        public IActionResult Edit(int id)
        {
            if (id == 0 )
            {
                return NotFound();
            }

            var expenseCategory = _expense.GetById(id);
            if (expenseCategory == null)
            {
                return NotFound();
            }
            return View(expenseCategory);
        }

        // POST: ExpenseCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public IActionResult Edit(int id, ExpenseCategory expenseCategory)
        {
            if (id != expenseCategory.ExpenseCategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _expense.Update(expenseCategory);
                }
                catch (DbUpdateConcurrencyException)
                {
                    return View(expenseCategory);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(expenseCategory);
        }

        // GET: ExpenseCategories/Delete/5
        public IActionResult Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var expenseCategory =  _expense.GetById(id);
            if (expenseCategory == null)
            {
                return NotFound();
            }

            return View(expenseCategory);
        }

        // POST: ExpenseCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {

            _expense.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private bool ExpenseCategoryExists(int id)
        {
          return _expense.GetById(id).Equals(null);
        }
    }
}

ExpenseTracker/Controllers/ExpenseCategoryController.cs
using ExpenseTracker.Repository;
using Microsoft.AspNetCore.Mvc;

namespace ExpenseTracker.Controllers
{
    public class ExpenseCategoryController : Controller
    {
        private readonly IExpenseCategory CategoryRepository;
        public IActionResult Index()
        {
            return View();
        }
    }
}

ExpenseTracker/Controllers/HomeController.cs
using ExpenseTracker.Models;
using ExpenseTracker.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;

namespace ExpenseTracker.Controllers
{
    public class HomeController : Controller
    {
        private readonly IExpense Repository;
        private readonly IExpenseCategory ExpenseRepository;
        //private readonly ILogger<HomeController> _logger;

        //public HomeController(ILogger<HomeController> logger)
        //{
        //    _logger = logger;
        //}

        public HomeController(IExpense repository,IExpenseCategory expenseRepository)
        {
            Repository = repository;
            ExpenseRepository = expenseRepository;
        }

        public IActionResult Index()
        {
            
            var expenses = Repository.GetAll();
            return View(expenses);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.ExpenseCategories = new SelectList(ExpenseRepository.GetAll().ToDictionary(us => us.ExpenseCategoryId, us => us.ExpenseCategoryName), "Key", "Value");

            return View();
        }

        [HttpPost]
        public IActionResult Create(Expense exp)
        {
            var AlreadyExists = Repository.GetAll().Where(x => x.ExpenseCategoryId == exp.ExpenseCategoryId).FirstOrDefault();
            if (AlreadyExists == null)
            {

                Repository.Create(exp);
                return RedirectToAction("Index");
            }
            else
            {

                ViewBag.Message = string.Format(" This Category Is Already Exists !!! Firstly, Please CREATE New Category In EXPENSE CATEGORY Page ", exp);
                return View();
            }
           
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {

            var exp= Repository.GetById(id);
            return View(exp);
        }
        [HttpPost]
        public IActionResult Edit(Expense exp)
        {

            Repository.Update(exp);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            
            Repository.Delete(id);
            return RedirectToAction("Index");
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExpenseTracker/Views/ExpenseCategories/Create.cshtml
@model ExpenseTracker.Models.ExpenseCategory

@{
    ViewData["Title"] = "Create";
}


<div class="row">
    <div class="col-md-4">

@*        @using (Html.BeginForm("Create","ExpenseCategoriesController",FormMethod.Post))
        {*@
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ExpenseCategoryName" class="control-label"> Expense Category Name</label>
                <input asp-for="ExpenseCategoryName" class="form-control" />
                <span asp-validation-for="ExpenseCategoryName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
               @* <input type="text" id="txtName" name="name" />*@
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
           
           
        </form>
        @if (ViewBag.Message != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    alert("@ViewBag.Message");
                };
            </script>
        }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExpenseTracker/Views/ExpenseCategories/Delete.cshtml
@model ExpenseTracker.Models.ExpenseCategory

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ExpenseCategory</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpenseCategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpenseCategoryName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ExpenseCategoryId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ExpenseTracker/Views/ExpenseCategories/Edit.cshtml
@model ExpenseTracker.Models.ExpenseCategory

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ExpenseCategory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ExpenseCategoryId" />
            <div class="form-group">
                <label asp-for="ExpenseCategoryName" class="control-label"></label>
                <input asp-for="ExpenseCategoryName" class="form-control" />
                <span asp-validation-for="ExpenseCategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExpenseTracker/Views/ExpenseCategories/Index.cshtml
@model IEnumerable<ExpenseTracker.Models.ExpenseCategory>

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                Expense Category Name
            </th>
            <th >Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ExpenseCategoryName)
            </td>
            <td>
                <a asp-action="Edit" class="btn btn-info" asp-route-id="@item.ExpenseCategoryId">Edit</a> |
                @*<a asp-action="Details" asp-route-id="@item.ExpenseCategoryId">Details</a> |*@
                <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.ExpenseCategoryId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ExpenseTracker/Views/ExpenseCategory/Index.cshtml
@model IEnumerable<ExpenseTracker.Models.ExpenseCategory>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ExpenseCategoryId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpenseCategoryName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ExpenseCategoryId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpenseCategoryName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

ExpenseTracker/Views/Home/Create.cshtml
@model ExpenseTracker.Models.Expense

@{
    ViewData["Title"] = "Create";
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DateOfExpense" class="control-label">Date Of Expense</label>
                <input asp-for="DateOfExpense" type="date" id="dateFeild" max="2022-10-02" class="form-control" />
                <span asp-validation-for="DateOfExpense" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpenseAmount" class="control-label"> Expense Amount</label>
                <input asp-for="ExpenseAmount" class="form-control" />
                <span asp-validation-for="ExpenseAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpenseCategoryId" class="control-label">Expense Category</label>
                <select id="ExpenseCategoryId" Name="ExpenseCategoryId" class="form-control" asp-items="ViewBag.ExpenseCategories"></select>
                <span asp-validation-for="ExpenseCategoryId" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        @if (ViewBag.Message != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    alert("@ViewBag.Message");
                };
            </script>
        }
    </div>
</div>

<div>
    <a asp-action="Index" style="text-decoration:none">Back to List</a>
</div>
<script>
    var today = new Date();
    var dd = today.getDate();
    var mm = today.getMonth() + 1; //January is 0!
    var yyyy = today.getFullYear();
    if (dd < 10) {
        dd = '0' + dd
    }
    if (mm < 10) {
        mm = '0' + mm
    }

    today = yyyy + '-' + mm + '-' + dd;
    document.getElementById("dateFeild").setAttribute("max", today);
                //alert("test");
</script>





@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }
    

ExpenseTracker/Views/Home/Edit.cshtml
@model ExpenseTracker.Models.Expense

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Expense</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ExpenseId" class="control-label"></label>
                <input asp-for="ExpenseId" class="form-control" />
                <span asp-validation-for="ExpenseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfExpense" class="control-label"></label>
                <input asp-for="DateOfExpense" class="form-control" />
                <span asp-validation-for="DateOfExpense" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpenseAmount" class="control-label"></label>
                <input asp-for="ExpenseAmount" class="form-control" />
                <span asp-validation-for="ExpenseAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpenseCategoryId" class="control-label"></label>
                <input asp-for="ExpenseCategoryId" class="form-control" />
                <span asp-validation-for="ExpenseCategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExpenseTracker/Views/Home/Index.cshtml
@model IEnumerable<ExpenseTracker.Models.Expense>

@{
    ViewData["Title"] = "Index";
}


<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
    <br />
</p>
<table class="table table-hover">
    <thead>
        <tr>
            
            <th>
               Date of expense
            </th>
            <th>
                Amount
            </th>
            <th>
                Category Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfExpense)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpenseAmount)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.ExpenseCategory.ExpenseCategoryName)
            </td>
                
                @*<span asp-validation-for="ExpenseCategoryName" class="text-danger"></span>*@
            <td>
                    @Html.ActionLink("Edit", "Edit", new {  id=item.ExpenseId  }) |
                  @*  @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                    @Html.ActionLink("Delete", "Delete", new {  id=item.ExpenseId  })
            </td>
        </tr>
}
    </tbody>
</table>

ExpenseTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpenseTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpenseTracker.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExpenseTracker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExpenseCategories" asp-action="Index">Expense Catagory</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ExpenseTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>